val test1 = longest_string1 [] = ""
val test2 = longest_string1 ["sfsdafefeAe","basdfefc","Csadfef"] = "sfsdafefeAe"
val test3 = longest_string1 ["Aas","bcd","Cdf"] = "Aas"
val test4 = longest_string1 ["A","bcasdfe","Casfdefesafa","dasf"] = "Casfdefesafa"
val test5 = longest_string1 ["A","bc","C"] = "bc"